### ISSUE TITLE
Getting the value of the input

### ISSUE THREAD

**Issue by abigwonderful** [tbleckert/react-select-search#2]
Please excuse my ignorance if it's right in front of my face... vary new to react here!

After i've selected one of the options from the array, how do I access that value?

Any guidance much appreciated!

(in my case i'd like to update my state/redux store with the input value)

**Comment by tbleckert** [comment]
The documentation could definitely say more.

 The react component renders an input element with the name equal to the name property. You can get the value from that element and it also works in normal form submits. If it's a multiple select, the component will render a hidden multiple select to mimic the values.

You can also use the event `valueChanged`. This is called when the value changes and has the option object as the first argument.

```javascript
function onValueChanged(option, state) {
    console.log(option); // {name: "English", value: "en"}

    // If it's a multiple select, you can get all selected options with state.value
}

<SelectSearch name="languages" valueChanged={onValueChanged} />
```

So if you use this component as a child component, you would use `valueChanged` to update the state on the main component.

Examples can be found in the demo page:  
http://tbleckert.github.io/react-select-search/  
https://github.com/tbleckert/react-select-search/blob/gh-pages/bootstrap.js

Please close this if it answers your question, otherwise just get back to me.

**Comment by abigwonderful** [comment]
thanks for the quick response. That was exactly what i needed!
```
valueChanged={onValueChanged}

**Comment by hatyaiapp** [comment]
@tbleckert `valueChanged` is not working now. what should I do

**Comment by AlexBasile123** [comment]
valueChanged has been removed, right? It's not in the api description on github. Also tried it to just to make sure.
