### ISSUE TITLE
Allow virtualized options

### ISSUE THREAD

**Issue by rob10e** [tbleckert/react-select-search#23]
Great component, unfortunately I cannot use it with the size of the list I have. If the options could be virtualized, it would be perfect.

**Comment by tbleckert** [comment]
Thanks! It has been on my agenda for a while. I think I was just waiting for someone to mention it as a kick in the butt..Shouldn't take too much time to implement. I'll keep you posted. Also feel free to send a PR if you want to.

**Comment by rob10e** [comment]
Thank you. I look forward to using it when completed. :)

**Comment by tbleckert** [comment]
Lots has happened since this issue was created. Not sure I want to bloat the package by bringing in a third-part library like react-virtualized that is ~30kb min+gzipped.

Since we now have hook support, I believe this is more suited as a third-part implementation that utilizes the `useSelect` hook together with react-virtualized.

I'm closing this for now, if anyone disagrees feel free to comment on this issue.

**Comment by sid-kap** [comment]
I managed to create a virtualized version of this and it works really well! However I didn't want to implement input management, fuzzy search, etc. myself so I ended up just taking SelectSearch.js and modifying a few lines as needed: https://gist.github.com/sid-kap/3d47b06891e8b8c1c7de402b422e484b

Do you think there's a way we could modify react-select-search that makes this sort of change possible without having to copy the SelectSearch code?

The changes I had to make for react-window were:
* Replace the `<ul>` with a `FixedSizeList`
* Take the lambda that was inside `options.map((option) => ... )`, and break it out into a function that I pass as the list body to FixedSizeList. The body of the lambda is basically the same, but instead of looping ourselves we give the lambda to `FixedSizeList`, and it is then called with the indices of the options that need to be rendered.
* For each item, `FixedSizeList` gives us both the index (an int) and a `style` argument that includes the absolute positioning offset. I just added that to `optionProps` so that it gets added to the style inline.

**Comment by tbleckert** [comment]
Nice work! I've refactored a lot of the code in v3 (next branch), mainly some optimizations but also moved code into separate components like; Options, Option and Value.

Maybe we could make a separate options component, like `VirtualizedOptions`. Then we could have an option for using it. That way, react-window could be an optional dependency and we wouldn't increase the size thanks to tree shaking.

Another option would be to make the components (Options, Option and Value) pluggable via options. Then you could just pass your own options component that is powered by react-window. A way to make community driven plugins.

What do you think?

**Comment by sid-kap** [comment]
Either of those sounds great to me!
