### ISSUE TITLE
clear input

### ISSUE THREAD

**Issue by abigwonderful** [tbleckert/react-select-search#5]
hey man,
i'm trying to think of a clever way to clear the input onclick (button). Any thoughts on the best way to approach this?

**Comment by tbleckert** [comment]
Which input do you want to clear? Either way, the correct way of changing states in React is by doing a re-render. So I would suggest that the select search component is a child component of a larger component, a form for example. If the button lives in the same component, you could just have an onclick handler on it. If it's somewhere else you could just add an event listener.

Hope that answers your question. Please close if it helps you, otherwise just let me know.

**Comment by abigwonderful** [comment]
Sorry wasn't very clear. Here is a visual to support.

Basically the issue I'm having is that a value is selected and added to a list. Once I've added it to the list, I want to clear it from the select-search input. You may notice that when I go to search for another name, the last selected stays at the top even though it does not match the input as I type.

Is there a native method to the select-search that I could call to clear out the input (and previously selected value)?
![gif of form](http://g.recordit.co/V8AXwpfiAF.gif)

**Comment by tbleckert** [comment]
There's no API to edit the state of the component. The correct way is to re-render the component. In your example, the select component and the button should be in a component.

```javascript
constructor(props) {
    super(props);

    this.state = {
        human: ''
    };
}

onChange(value) {
    this.setState({human: value.value});
}

addHuman() {
    // Do what you do then clear the currently selected option
    this.setState({human: ''});
}

render() {
    return (
        <div>
            <SelectSearch value={this.state.human} onChange={this.change} .../>
            <button onClick={this.addHuman}>+ add</button>
        </div>
    );
}
```

Not tested but you get the idea. This component is meant to work as a child in another component, like the form you have. So the props acts as the API since it causes a rerender (when needed). Updating the value prop to an empty string will clear the input.
