### ISSUE TITLE
How use `id` filed as option value ?

### ISSUE THREAD

**Issue by ulugbekrozimboyev** [tbleckert/react-select-search#51]
Hello everyone.
In my case I have a list of objects like that:
`[{  id: 1, first_name: 'anyname'} , ... ]`
 
I have 

 `<SelectSearch
                            name="userId"
                            className="select-search-box"
                            // multiple
                            value={0}
                            height={172}
                            customEntries={true}
                            fuse={defaultFormData.userSearchObj}
                            options={ users.length ? users : [{ id: 0, first_name: '' }] }
                            renderOption={option => option ? ${option.first_name}}
                            renderValues={option => option.id }
                          />`

but when I select one item all items became selected. How can I fix this situation ?

**Comment by tbleckert** [comment]
Hi @ulugbekrozimboyev !

The `value` property is required in the options objects. `renderValues` is also not an available prop, so that function won't do anything.

I suggest you map your options array before you pass it.

```javascript
const options = (users.length) ? users.map(user => ({
    value: user.id,
    name: user.first_name,
}) : [{ value: 0, name: '' }];
```

I hope that helps. Let me know if the documentation is unclear about something. You are allowed to pass whatever props you want in your options, but they're are only used in search and rendering.

**Comment by ulugbekrozimboyev** [comment]
Thanks bro, it's working

**Comment by tbleckert** [comment]
@ulugbekrozimboyev Awesome!
