### ISSUE TITLE
Can't get selected value.

### ISSUE THREAD

**Issue by Phon1209** [tbleckert/react-select-search#60]
Sorry for a silly question, but I can't figure how to get value from it.

**Comment by tbleckert** [comment]
@Phon1209 Not a silly question at all. You get it by setting an `onChange` handler. Like this:

```
<SelectSearch onChange={(value) => console.log(value)} />
```

**Comment by arkzky** [comment]
Your question is not silly at all!!

I was strugling with the same issue. It was confusing to me because I had tried several other libraries in which they use a "selectedValue" prop to get the user selected value. 

This time around seems like they decided to stick with the default method to get values from vanilla HTML select in React, which is good  but kind of rare to me this days 😅
