### ISSUE TITLE
cannot select the first item with keyboard

### ISSUE THREAD

**Issue by mertenhanisch** [tbleckert/react-select-search#7]
Chrome 51, Firefox 46, Safari 9.0.3 on Mac OS 10.10.5
* visit [demo page](http://tbleckert.github.io/react-select-search/)
* click the country selection field
* type `ger`
* press down key once to focus `Germany`
* press enter

Result: Nothing happens
Expected behaviour would be that it selects `Germany` as it does when clicking the item.

**Comment by tbleckert** [comment]
Thank you!

I'm about to release a new version that fixes a lot of stuff, will make sure this works in the new release. I decided to rewrite large portions of the code since there's still left overs from the es6 transition and also crappy focus management. I will keep you posted, thanks for reporting this.

**Comment by mertenhanisch** [comment]
That sounds great! Any idea, when this might be coming out? Should I close this issue then or are you going to close it, when the new version is coming out (so others know, what is going on)?

**Comment by tbleckert** [comment]
I'm keeping this open so we can close it when it's confirmed that this is no longer a problem in the new release. I'm hoping to finish this release by the end of this week

**Comment by tbleckert** [comment]
I've release a new version now (0.5.0) that includes better keyboard handling. The demo page is also updated. If the issue is gone, please close this issue.

**Comment by mertenhanisch** [comment]
Thanks a lot! It works now :)
